packages:
  - experiments/**
  - mp-platform/**
  - packages/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - lmdb
  - msgpackr-extract
  - re2
  - unrs-resolver
